config/routes.rb
Rails.application.routes.draw do
  root 'blogs#index'
  devise_for :users
  resources :blogs do
  	resources :likes
   resources :comments
end
   	resources :replies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
	belongs_to :user
	has_many :likes, dependent: :destroy
	has_many :comments , dependent: :destroy
	mount_uploader :image, ImageUploader
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  has_many :replies, dependent: :destroy
  belongs_to :user
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :blog
  belongs_to :user
end

app/models/reply.rb
class Reply < ApplicationRecord
  belongs_to :comment 
  belongs_to :user
  validates :body	, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :blogs 
	has_many :likes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	  before_action :authenticate_user!, only: [:create, :edit, :update, :destroy, :new]
	before_action :configure_permitted_parameters, if: :devise_controller?
protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  # GET /blogs
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  def show
    @blog = Blog.find_by(id: params[:id])
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    @blog.save
    redirect_to blogs_path
  end

  def update
    @blog.update(blog_params)
    redirect_to @blog
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path
  end

  private
    def set_blog
      @blog = Blog.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :body, :image , :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.new(comment_params)
    @comment.user_id = current_user.id
    @comment.save
    redirect_to blog_path(@blog)
  end

 def destroy
    @blog = Blog.find(params[:blog_id])
    @comment = @blog.comments.find(params[:id])
    @comment.destroy
    redirect_to blog_path(@blog)
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
before_action :find_blog
before_action :find_like, only: [:destroy]

	def create
	  if already_liked?
	    flash[:notice] = "You can't like more than once"
	  else
	   @blog.likes.create(user_id: current_user.id)
	  end
	  redirect_to blog_path(@blog)
	end

	def destroy
		  if !(already_liked?)
		    flash[:notice] = "Cannot unlike"
		  else
		    @like.destroy
		  end
		  redirect_to blog_path(@blog)
	end

	def find_like
   		@like = @blog.likes.find(params[:id])
	end

  private
 	 def already_liked?
	  Like.where(user_id: current_user.id, blog_id:
	  params[:blog_id]).exists?
	end

 	def find_blog
    	@blog = Blog.find(params[:blog_id])
  	end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController

	def create
		@reply = Reply.new
		@reply.body = params[:reply][:body]
		@reply.comment_id = params[:comment_id]
		@reply.user_id = current_user.id
		@reply.save
		@blog  = Comment.find(params[:comment_id]).blog
		redirect_to @blog
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
 <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

<%= form.submit class: 'btn btn-primary' %>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-sm-6">
    <h1>Blogs</h1>
  </div>

  <div class="col-sm-6 text-right">
  <%= link_to new_blog_path, class: 'btn btn-primary' do %>
    Add New Post
  <% end %>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
    

            <th>Title</th>
            <th>Body</th>
            <th>Image</th>
            <th>Posted By</th>
          <th></th>
        
      </tr>
    </thead>

    <tbody>
       <% @blogs.each do |blog| %>
        <%= content_tag :tr, id: dom_id(blog), class: dom_class(blog) do %>
          

                      <td><%= blog.title %></td>
                      <td><%= blog.body %></td>
                  <% if blog.image_url %>
                    <td><%= image_tag blog.image.url(:thumb) %></td>
                  <%else%>
                    <td><img src="" alt="no image for blog"></td>
                    <% end %>
           <td><%= blog.user.name %></td>
            <td><%= link_to 'Show', blog %>
              <%if current_user%>
           <%if blog.user_id == current_user.id %>
            <%= link_to 'Edit', edit_blog_path(blog) %>
            <%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <%end%>
        <%end%>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/blogs/new.html.erb
<h1>Add Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container page-header">
  <%= link_to 'All Blogs' ,blogs_path  %>
  <%if current_user%>
  <% if @blog.user_id == current_user.id %>
  <%= link_to edit_blog_path(@blog) , class: 'btn btn-primary' do %>
  <span class="glyphicon glyphicon-pencil"></span>
  Edit
  <% end %>
  <% end %>
  <%end%>
  <%= link_to 'Back', blogs_path %>
  <h1>Show Blog</h1>
</div>
<dl class="container">
  <dt>Title:</dt>
  <dd><%= @blog.title %></dd>
  <dt>Body:</dt>
  <dd><%= @blog.body %></dd>
  <dt>Image</dt>
  <dd>
    <% if @blog.image_url %>
    <td><%= image_tag @blog.image.url(:thumb) %></td>
    <%else%>
    <td><img src="" alt="no image for blog"></td>
    <% end %>
    <%if current_user.present? %>
    <p><%= @blog.likes.count %> <%= (@blog.likes.count) == 1 ? 'Like' : 'Likes'%>
      <% pre_like = @blog.likes.find { |like| like.user_id == current_user.id} %>
      <% if pre_like %>
      <%= link_to '', blog_like_path(@blog, pre_like), method: :delete ,class: "fa fa-thumbs-down fa-3x" %>
      <% else %>
      <%= link_to '', blog_likes_path(@blog), method: :post, class: "fa fa-thumbs-up fa-3x"%>
      <% end %>
    </p>
    <%else%>
    <p><%= @blog.likes.count %> <%= (@blog.likes.count) == 1 ? 'Like' : 'Likes'%>
      <%= link_to '', blog_likes_path(@blog), method: :post, class: "fa fa-thumbs-up fa-3x"%>
    </p>
    <%end%>
  </dd>
</dl>
<h2>Comments</h2>
<%= form_with(model: [ @blog, @blog.comments.build ], local: true) do |form| %>
<div class="form-group">
  <%= form.text_area :body, class: 'form-control' %>
</div>
<%= form.submit class: 'btn btn-primary' %>
<% end %>
<br />
<div class="container">
  <% @blog.comments.each do |comment| %>
  <%if comment.persisted? %>
  <strong><%= comment.user.name rescue nil %></strong> <%= link_to "commented" %>
  <div class="row">
    <div class="col-md-2"><%= simple_format comment.body %></div>
    <div class="col-md-2">
      <%= link_to 'Delete', [comment.blog, comment],
        method: :delete,
        data: { confirm: 'Are you sure?' } %>
    </div>
    <div class="mydiv" >
      <%= form_for :reply , url: replies_path(comment_id: comment.id), method: :post do |f| %>
      <%= f.text_field :body %>
      <%= f.submit "reply" , class: "btn btn-primary"%>
      <% end %>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
          <% comment.replies.each do |reply| %>
          <br />
          <strong>   <%= reply.user.name  rescue nil %> </strong> <%= link_to "replied" %> <%= reply.body %>
          <%end%>
        </div>
      </div>
    </div>
  </div>
  <%end%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BloggerApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="col-md-12 text-right">
     <% if user_signed_in? %>
 
  <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>        

<% else %>
 <%= link_to 'Register', new_user_registration_path, class: "btn btn-primary" %>
  <%= link_to 'Login', new_user_session_path, class: "btn btn-primary" %>  

<% end %>
  </div>

    <%= yield %>
    <div class="footer"style="padding: 10%;"></div>
  </body>
</html>